### ISSUE TITLE
Bashisms, poor shell style...

### ISSUE THREAD

**Issue by onlyjob** [Korkman/storage-tuner-benchmark#1]
Script is full of bashisms, needless `function` keywords, poor `echo` style, tabs, long and sometimes needlessly nested if-else, etc.
Please consider running `shellcheck`; add `set -u` to the beginning (and perhaps `set -e` as well). 
Thanks.

**Comment by Korkman** [comment]
Thanks for the feedback. I'm still writing out the readme, documenting the fio params and their goals. It's not the most beautiful script, true, but it's compact in lines so should be readable for everyone. As for the echo style, how would you format output?

**Comment by Korkman** [comment]
shellcheck and checkbashisms look good now. @onlyjob can you test on BSD or Solaris? Also, reduced output very much, it's all about IOPS now.

**Comment by Korkman** [comment]
Tested and fixed for FreeBSD and Open Indiana. Should be portable now. Also, much better looking. Not poor shell style anymore :-p
